version: 2

sources:
  - name: test
    database: dbt
    schema: dbt_models
    tables:
      - name: new_test
  - name: airbyte
    database: airbyte
    schema: airbyte_sources
    tables:
      - name: sources__customers
      - name: sources__orders
      - name: sources__order_details
      - name: sources__products


