version: 2

sources:
  - name: test
    database: dbt
    schema: dbt_models
    tables:
      - name: new_test


# sources:
#   - name: airbyte
#     database: airbyte
#     schema: airbyte_sources
#     tables:
#       - name: customers
#       - name: products
#       - name: orders
#       - name: order_details
